name: Sync from main to echo
on:
  push:
    branches:
      - other

jobs:
  sync-branches:
    runs-on: ubuntu-latest
    name: Syncing branches
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 18
      - name: Opening pull request
        id: pull
        uses: tretuna/sync-branches@main
        with:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          FROM_BRANCH: "main"
          TO_BRANCH: "echo-main"
          PULL_REQUEST_AUTO_MERGE_METHOD: "merge"
