name: Sync from main to other
on:
  push:
    branches:
      - main

jobs:
  sync-branches-echo:
    runs-on: ubuntu-latest
    name: Syncing to echo-main
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Git Setup
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      - name: Rebase main to echo-main
        run: |
          git fetch origin
          git checkout echo-main
          git rebase main
          git push origin echo-main
